[project]
id = "sieve"
name = "Mach Sieve"
version = "0.3.0"
dir_src = "src"
dir_dep = "dep"
dir_out = "out"
target = "native"

[targets.linux]
os = "linux"
isa = "x86_64"
abi = "sysv64"
mode = "executable"
entrypoint = "main.mach"
artifacts = "linux"
binary = "linux/bin/sieve"

[deps.mach-std]
type = "remote"
path = "https://github.com/octalide/mach-std"
version = "branch/dev"
