[project]
id      = "sieve"
name    = "Mach Sieve"
version = "0.4.1"
src     = "src"
dep     = "dep"
target  = "native"
out     = "out/{target}/bin/{name}{ext}"
obj     = "out/{target}/obj"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[bin.sieve]
entry = "main.mach"

[deps.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
